{
 "title": "Rental Prediction",
 "time": { "from": "2025-07-17T11:05:54.870Z", "to": "2025-07-17T11:06:16.925Z" },
 "panels": [
  {
   "title": "Drifted Column",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT num_drifted_columns, \"timestamp\" FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Prediction Drift",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", prediction_drift FROM metrics LIMIT 50 "
    }
   ]
  },
  {
   "title": "Missing Values",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT \"timestamp\", share_missing_values FROM metrics LIMIT 50 "
    }
   ]
  }
 ]
}